import { Sometype_Mono, Sometype_Mono } from "next/font/google";
import "./globals.css";

//Components
import MainNav from "@/components/MainNav";
import PageTransition from "@/components/PageTransition";
import RetangleTransition from "@/components/RetangleTransition";
import Gradient from "@/components/Gradient";
import Header from "@/components/Header";


const sometypeMono = Sometype_Mono({
  variable: "--font-sometypeMono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Samyra - Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${sometypeMono.variable} antialiased overflow-hidden relative`}>
        <Gradient />
        <RetangleTransition />
        <PageTransition>
        <div className="flex">
        {/* main nav */}
          <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
            <MainNav />
          </div>
        <div className="w-full max-w-[1130px] px-[15px] mx-auto">
          <Header />
        <div>{children}</div>
        </div>
        </div>
        </PageTransition>
      </body>
    </html>
  );
}
